xerial/snappy-java

Makefile.common
This is an identical copy of the Linux_ppc64 config, except that it has -m32 instead of -m64, and that it doesn't use `lib/inc_ibm/jni_md.h` which breaks 32-bit builds due to the removed definition of jlong for the 32-bit case.
Also, I added the missing -m64 to the second definition of `Linux-ppc64_CXXFLAGS`.
=> Add native library for ppc (32 bit)

src/test/java/org/xerial/snappy/SnappyOutputStreamTest.java
This commit adds a failing regression test which demonstrates the issue reported in #100.  This test asserts that the size of the compressed SnappyOutputStream output should only depend on the size and contents of the input and not on how many separate `write()` calls are used to pass that input to the output stream.
=> Add failing regression test for #100

src/main/java/org/xerial/snappy/SnappyOutputStream.java, src/test/java/org/xerial/snappy/SnappyOutputStreamTest.java
=> Stabilize compressed data size of SnappyOutputStream

src/main/java/org/xerial/snappy/SnappyLoader.java
Just faced with the problem when the temp directory doesn't exist at the beginning and FileOutputStream constructor throws an exception at line 212. I believe this should fix it, though I haven't tested it.
=> Fix FileNotFoundException while writing the library file

src/main/java/org/xerial/snappy/SnappyOutputStream.java, src/test/java/org/xerial/snappy/SnappyOutputStreamTest.java
This patch will fix #107, an issue where `SnappyOutputStream.close()` is not idempotent.
The first commit is a failing regression test which shows how a non-idempotent `close()` can lead to stream corruption issues.
=> Make SnappyOutputStream.close() idempotent; guard against writing to closed stream

build.sbt
#116 
x86_64 might be recognise as x64 or amd64 on some servers... osgi the fails to load native dependencies!
=> Support amd64 arch under windows & linux

src/test/java/org/xerial/snappy/SnappyOutputStreamTest.java
=> Fix SnappyOutputStreamTest for big-endian platforms

sbt
The original version in snappy-java had a hardcoded URL and curl wasn't being run with the --location option. This version from upstream (https://github.com/paulp/sbt-extras) fixes both issues, among other things.
=> Upgrade sbt script; the old version could no longer download SBT properly

build.sbt
The project url in the pom file was broken.
=> Fix small typo in pom project url

lib/inc_linux/jni.h
Current jni.h for linux has GPL licence. The latest one from Oracle does not. In general GPL license prevents the snappy jar from distribution. This change remove that restriction.
=> Replace jni.h with the latest from Oracle.

README.md
Update links to `framing_format.txt` to Google's snappy GitHub project
=> README.md: fix dead Google Code links

.travis.yml, project/build.properties, src/main/java/org/xerial/snappy/SnappyInputStream.java
For avoiding JNI overhead, reported in apache/spark#12074
=> Use non-JNI method for read(byte[])

Makefile
In the current master, `make` fails on max_x86-64 platforms because;
```
make: *** No rule to make target `target/snappy-1.1.3-Mac-x86_64/snappy-sinksource.o', needed by `target/snappy-1.1.3-Mac-x86_64/libsnappyjava.jnilib'.
```
This pr fixes this issue.
=> Add a missing entry in Makefile

Makefile
See #186.
I think these changes are needed on any platform.  The reason you may not have seen this problem on your platform is probably that your system has the snappy header files installed and the compiler refers not to target/snappy-1.1.7-*/snappy-stubs-public.h but to /usr/include/snappy-stubs-public.h.
=> Run snappy-header target to generate snappy-stubs-public.h

Makefile, Makefile.common, lib/include/config.h
Now that the build process runs cmake on any platform, I think config.h and snappy-stub-public.h generated by cmake should be used throughout the platforms. This PR will allow s390x to use SNAPPY_IS_BIG_ENDIAN defined in config.h.
Please correct me if my understanding about the build process is wrong....
=> Use config.h and snappy-stubs-public.h generated by cmake

src/main/java/org/xerial/snappy/SnappyOutputStream.java
Add more information about output data format.
besides writing the snappy magic header (8 bytes) described in
```
new byte[] {-126, 'S', 'N', 'A', 'P', 'P', 'Y', 0}
```
We also need to write another 8 bytes: 2 integers each with 4 bytes representing version and compatible version. The version should at least be 1.
---- I think the above information should be added to the SnappyOutputStream.
See #205
=> [DOC] Optimize SnappyOutputStream java doc

build.sbt
Fixes #210
`osgiSettings` is apparently required, per sbt-osgi docs:
> To also override the default publish behaviour, also add the osgiSettings settings to your project via your preferred method.
Also I noticed that the version of sbt-osgi used now includes a 'Require-Capability' section to the manifest.  The default behavior of OSGi is to use the version of java you are compiling the project with, i.e.:
> Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
Since the project works with java 1.7, I added an explicit entry for 1.7.
Finally I noticed that the path to the libsnappyjava.so library for `arm_le` was incorrect, it should be `armv7` instead of `arm7`
Example of manifest generated:
```
Manifest-Version: 1.0 …
```
=> Add OSGi bundle metadata to manifest

src/main/java/org/xerial/snappy/SnappyFramed.java
Address https://github.com/xerial/snappy-java/issues/224 by using api available in java 9 (if present) to release direct byte buffer
=> java 9 valid direct byte buffer release

.gitignore, Makefile
This allows it to build on JDK10+. `javac` supports `-h` since JDK8, though, so using Java 8 will still work.
=> Use javac -h instead of javah

src/main/java/org/xerial/snappy/SnappyFramed.java, src/main/java/org/xerial/snappy/SnappyFramedInputStream.java, src/main/java/org/xerial/snappy/SnappyFramedOutputStream.java, src/main/java/org/xerial/snappy/pool/BufferPool.java, src/main/java/org/xerial/snappy/pool/CachingBufferPool.java, src/main/java/org/xerial/snappy/pool/DefaultPoolFactory.java, src/main/java/org/xerial/snappy/pool/DirectByteBuffers.java, src/main/java/org/xerial/snappy/pool/QuiescentBufferPool.java, src/test/java/org/xerial/snappy/pool/CachingBufferPoolTest.java
Pool byte[] and direct ByteBuffer instances for reuse by Framed
implementation.
https://github.com/xerial/snappy-java/issues/233
=> Pool byte[] and direct ByteBuffer

.travis.yml
As Travis CI [officially supports](https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z) s390x builds, adding support for same.
=> Adding s390x support in Travis

Makefile.common
I would like `-static-libstdc++` on LINKFLAGS for aarch64 to fix [BIGTOP-3397](https://issues.apache.org/jira/browse/BIGTOP-3397) (packaging failure of Spark on CentOS 7(aarch64)).
=> Add -static-libstdc++ on LINKFLAGS of aarch64

Makefile, docker/Makefile
`make mac64` fails as reported in #257 . The cause is version mismatch of cmake.
```
$ make mac64
...
cd target/snappy-1.1.7-Mac-x86_64 && cmake  ../../target/snappy-1.1.7
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
CMake 3.1 or higher is required.  You are running version 3.0.2
```
Using latest multiarch/crossbuild based on Debian stretch should fix this.
=> Fix failure of make mac64 due to version mismatch of cmake

src/main/java/org/xerial/snappy/pure/PureJavaSnappy.java
This fixes https://github.com/xerial/snappy-java/issues/270
=> Pool table instances to make PureJavaSnappy thread safe

src/main/java/org/xerial/snappy/PureJavaCrc32C.java, src/main/java/org/xerial/snappy/SnappyFramed.java, src/main/java/org/xerial/snappy/SnappyFramedInputStream.java, src/main/java/org/xerial/snappy/SnappyFramedOutputStream.java, src/test/java/org/xerial/snappy/SnappyFramedStreamTest.java
java 9 introduced a jre implementation of crc32: https://docs.oracle.com/javase/9/docs/api/java/util/zip/CRC32C.html
The hotspot jvm also includes intrinsics for native optimizations. According to this issue[1], as long as you are on a recent version (last 2 years), the non-intrinsified implementation is ~2x faster than the hadoop pure java implementation (which is what PureJavaCrc32C is based on). The intrinsified implementation is another 2-3x faster than that.
[1] - https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8191328
=> prefer use of java.util.zip.CRC32C

Makefile.common
Added build risc-v configuration.
Tested this using qemu (Fedora32) and several applications like Spark.
=> Build on riscv64

.travis.yml
Adding support for IBM Power arch (ppc64le) in Travis which is supported natively on Power.
=> Adding ppc64le support in Travis

.github/workflows/test.yml
We are planning to upgrade the JDK to JDK 17 due to the performance issue:
https://bugs.openjdk.org/browse/JDK-8159720
This PR add Java 17 build test to GitHub action.
=> Add Java 17 build test to GitHub action

README.md
Also, I split the first line with badges into separated lines of mardown - it will be rendered same as one line but can be edited separately.
=> Fix links in Javadoc badge

.github/workflows/test.yml, build.sbt, src/main/java/org/xerial/snappy/Snappy.java
=> Fix java8 compatibility

src/main/java/org/xerial/snappy/SnappyLoader.java
=> add workaround for resource management issue in URLClassloader

src/test/java/org/xerial/snappy/SnappyTest.java
Updating SnappyTest.java and ignoring checks with arrays of large sizes.
To prevent java.lang.OutOfMemory errors from being caught during GitHub checks.
SnappyTest.java
=> CI Fix to Prevent Checks Dealing with Large Array Sizes

Makefile.common
@xerial observed an issue with the latest libsnappy.so file published with docker cross steps. When `lib/inc_linux/config.h` is included in s390x builds, the generated libsnappy.so fails to uncompress. This PR is for fixing the same. 
Wanted to confirm if this PR is merged, native-all (or linux-s390x) target will update native libraries to be included in next version jar, correct?
=> Update libsnappy.so for s390x

docker/dockcross-s390x
The `dockcross/linux-s390x:latest` docker image is currently used to cross compile the native library and the target lowest GLIBC version supported in the toolchain is v2.32. Hence, the version `GLIBC_2.32` not found issue would occur when the built s390x `libsnappyjava.so` was invoked in Linux distributions whose GLIBC version is lower than v2.32, such as RHEL (7, 8), SLES (12, 15) and Ubuntu 20.04.
This PR changed the `dockcross/linux-s390x` docker image to an earlier tag `20210210-84c47e5` in which the cross-compile toolchain is compatible with GLIBC v2.17, thus the built native library could work on the above-mentioned distributions, as well as newer distributions such as RHEL 9 or Ubuntu 22.04.
Fixes: https://github.com/xerial/snappy-java/issues/464
=> Fix the `GLIBC_2.32 not found` issue of `libsnappyjava.so` in certain Linux distributions on s390x

.github/workflows/test.yml
Simplifies workflow file, by using a matrix build
instead of separate build jobs with same steps.
=> Use matrix build for test workflow

src/main/java/org/xerial/snappy/SnappyFramedInputStream.java, src/main/java/org/xerial/snappy/SnappyFramedOutputStream.java
Tiny PR to fix the links in the Javadoc for `SnappyFramedInputStream` and `SnappyFramedOutputStream` which point to the old SVN location for the Snappy project on `googlecode` instead of the current Git repo location on GitHub.
=> Fix javadoc links to new url for framing_format.txt

src/main/resources/META-INF/native-image/org.xerial.snappy/snappy-java/resource-config.json
This PR adds GraalVM support to `snappy-java`
Documentation references:
* Accessing Resources in Native Image: https://www.graalvm.org/latest/reference-manual/native-image/dynamic-features/Resources/
* Native Image Build Configuration: https://www.graalvm.org/latest/reference-manual/native-image/overview/BuildConfiguration/
* Example implementation - AWS CRT: https://github.com/awslabs/aws-crt-java/pull/749
I added the files to this specific folder as it is going to be picked up by GraalVM automatically so you don't have to use `-H:ResourceConfigurationResources` - see the last comments of the "Example implementation" and the link of "Native image Build Configuration"
There are no `native-image.properties` required.
Fixes: https://github.com/xerial/snappy-java/issues/429
=> feat: add GraalVM support

src/main/java/org/xerial/snappy/SnappyFramed.java
currently we have written a lambda (turns into anonymous class) which invokes a MethodHandle for the java.util.zip.CRC32C constructor as the Supplier<Checksum> implementation.
This has 2 layers of misdirection. The Supplier implementation spun up by the jvm calls the anonymous lambda class, which then calls the MethodHandle invoke. This leads to stack traces like:
```
CRC32C.<init>() line: 126	
DirectMethodHandle$Holder.newInvokeSpecial(Object) line: not available	
Invokers$Holder.invokeExact_MT(Object, Object) line: not available	
SnappyFramed.lambda$0(MethodHandle) line: 48	
0x0000027d6201b320.get() line: not available	
SnappyFramed.getCRC32C() line: 76	
```
We can use LambdaMetafactory to generate a Supplier<Checksum> which calls the java.util.zip.CRC32C constructor directly. This …
=> use LambdaMetafactory to generate Supplier<Checksum> for java.util.zip.CRC32C instances

src/main/java/org/xerial/snappy/SnappyFramedInputStream.java
small performance improvement reading crc32c values in SnappyFramedInputStream by allowing the ByteBuffer to do the work. As these are direct ByteBuffer instances, this means only a single call across native boundary.
=> let ByteBuffer read 4 bytes as int in single call

src/main/resources/META-INF/native-image/org.xerial.snappy/snappy-java/resource-config.json
Hi!
I found an issue generating a native-image with graalvm. It seems for windows there's no native library included.
```
Error: Exception in thread "main" org.xerial.snappy.SnappyError: [FAILED_TO_LOAD_NATIVE_LIBRARY] no native library is found for os.name=Windows and os.arch=x86_64
at org.xerial.snappy.SnappyLoader.findNativeLibrary(SnappyLoader.java:345)
at org.xerial.snappy.SnappyLoader.loadNativeLibrary(SnappyLoader.java:179)
at org.xerial.snappy.SnappyLoader.loadSnappyApi(SnappyLoader.java:157)
at org.xerial.snappy.Snappy.init(Snappy.java:70)
at org.xerial.snappy.Snappy.<clinit>(Snappy.java:47)
at org.apache.parquet.hadoop.codec.SnappyDecompressor.maxUncompressedLength(SnappyDecompressor.java:34)
at org.apache.parquet.hadoop.codec.NonBlockedDecompressor.decompress(NonBlockedDecompres …
```
=> the dll is called snappyjava not libsnappyjava

src/main/java/org/xerial/snappy/BitShuffle.java, src/test/java/org/xerial/snappy/BitShuffleTest.java
=> Add bit-shuffling interfaces for unshuffle with provided output array

src/main/java/org/xerial/snappy/SnappyOutputStream.java
The change ensures that the default behavior is not duplicated within wrappers, improving maintainability and reducing redundancy.
=> Public`SnappyOutputStream` defaults

src/main/java/org/xerial/snappy/OSInfo.java
In a comment, update the link to Java bug #8005545, as the current one leads to a webpage saying: "This bug is not available."
=> OSInfo: Update link to Java bug #8005545

Makefile
This will allow snappy-java to build with JDK 21.
Resolves #532 (see discussion there for further details)
=> Change -source and -target parameters to Java 8
